### ISSUE TITLE
Erroring When Setting Up Live Sync Obsidian Plugin

### ISSUE THREAD

**Issue by jrpetersjr** [oleduc/docker-obsidian-livesync-couchdb#8]
I've followed the entire [step by step tutorial](https://leduccc.medium.com/setup-self-hosted-synchronization-for-obsidian-cba121166d5e). Everything seems to be working fine up until the final step of pasting in my setup url and passphrase and I get an error saying that it's unauthorized.

example Compose

```yml
version: "3.8"
services:
  couchdb-obsidian-livesync:
    image: docker.io/oleduc/docker-obsidian-livesync-couchdb:master
    container_name: obsidianlivesync
    restart: always
    environment:
      SERVER_URL: https://obsmdlivesync.mydomain.com
      COUCHDB_USER: user
      COUCHDB_PASSWORD: password
      COUCHDB_DATABASE: obsidiannotes
    ports:
      - 5984:5984
    volumes:
      - /dataforsaving:/opt/couchdb/data 
```

I have setup the _users database and NGINX Proxy Manager to point to my items. When I go to https://obsmdlivesync.mydomain.com/_utils I can see all of the settings are correct and the user database exists.

<img width="1336" alt="Image" src="https://github.com/user-attachments/assets/4aa874fe-f208-4793-a9de-b35baea54004" />

Next I copy paste the below into terminal.

```bash
docker run \
 -e hostname=https://obsmdlivesync.mydomain.com \
 -e database=obsidiannotes \
 -e username=user \
 -e password=password \
 -e passphrase=GetOverHere \
 docker.io/oleduc/docker-obsidian-livesync-couchdb:master \
deno -A /scripts/generate_setupuri.ts
```
I get something for a passphrase like 'snow-flower' and a setup url that is crazy long and when I paste that information into live sync plugin I get the following error:

<img width="411" alt="Image" src="https://github.com/user-attachments/assets/8ddd5f6f-8ee5-4640-9960-8d0b2dd3be94" />

TIA for any help you can provide.
